#!/usr/bin/env bash
# Simple wrapper so teammates can stand up Maestro via Terraform without prior knowledge.

set -euo pipefail

ACTION="${1:-apply}"
case "${ACTION}" in
  apply | plan | destroy) ;;
  *)
    echo "Usage: $0 [apply|plan|destroy]"
    echo "  apply   - builds the image (if needed) and creates/updates the Maestro container"
    echo "  plan    - shows the changes Terraform will make"
    echo "  destroy - stops the container and removes the image created by apply"
    exit 1
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/terraform"
CONFIG_FILE="${TF_DIR}/generated.auto.tfvars"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Error: '$1' is required but not installed or not on PATH."
    case "$1" in
      terraform)
        echo "Install Terraform from https://developer.hashicorp.com/terraform/downloads"
        ;;
      docker)
        echo "Install Docker Desktop or the Docker Engine (https://docs.docker.com/get-docker/)."
        ;;
    esac
    exit 1
  fi
}

tf_escape() {
  local value="${1}"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "${value}"
}

prompt_default() {
  local prompt="$1"
  local default="$2"
  local __resultvar="$3"
  local input
  read -r -p "${prompt} [${default}]: " input || true
  if [[ -z "${input}" ]]; then
    input="${default}"
  fi
  printf -v "${__resultvar}" '%s' "${input}"
}

prompt_optional() {
  local prompt="$1"
  local __resultvar="$2"
  local input
  read -r -p "${prompt} (leave blank to skip): " input || true
  printf -v "${__resultvar}" '%s' "${input}"
}

prompt_port() {
  local prompt="$1"
  local default="$2"
  local __resultvar="$3"
  local input
  while true; do
    read -r -p "${prompt} [${default}]: " input || true
    if [[ -z "${input}" ]]; then
      input="${default}"
    fi
    if [[ "${input}" =~ ^[0-9]+$ ]]; then
      printf -v "${__resultvar}" '%s' "${input}"
      break
    fi
    echo "Please enter numbers only."
  done
}

create_config_if_needed() {
  if [[ -f "${CONFIG_FILE}" ]]; then
    return
  fi
  if [[ ! -t 0 ]]; then
    echo "Configuration file ${CONFIG_FILE} is missing."
    echo "Run this script interactively once to generate it, or create your own .tfvars file."
    exit 1
  fi

  echo "No Terraform settings found. Let's capture a few basics (press Enter to accept defaults)."

  local container_name host_port_a host_port_b service_a_repo service_a_ref service_b_repo service_b_ref

  prompt_default "Container name" "maestro" container_name
  prompt_port "Host port for Service A (maps to container port 8080)" "8080" host_port_a
  prompt_port "Host port for Service B (maps to container port 9090)" "9090" host_port_b

  echo
  echo "Optional: bake code into the image during build."
  prompt_optional "Service A repository URL" service_a_repo
  if [[ -n "${service_a_repo}" ]]; then
    prompt_default "Service A branch or tag" "main" service_a_ref
  fi
  prompt_optional "Service B repository URL" service_b_repo
  if [[ -n "${service_b_repo}" ]]; then
    prompt_default "Service B branch or tag" "main" service_b_ref
  fi

  {
    echo "# Generated by provision.sh on $(date)"
    echo "image_name     = \"maestro-orchestrator\""
    echo "image_tag      = \"iac\""
    printf 'container_name = "%s"\n' "$(tf_escape "${container_name}")"
    if [[ -n "${service_a_repo}" ]]; then
      printf 'service_a_repo = "%s"\n' "$(tf_escape "${service_a_repo}")"
      printf 'service_a_ref  = "%s"\n' "$(tf_escape "${service_a_ref}")"
    fi
    if [[ -n "${service_b_repo}" ]]; then
      printf 'service_b_repo = "%s"\n' "$(tf_escape "${service_b_repo}")"
      printf 'service_b_ref  = "%s"\n' "$(tf_escape "${service_b_ref}")"
    fi
    cat <<EOF
ports = [
  {
    internal = 8080
    external = ${host_port_a}
    protocol = "tcp"
  },
  {
    internal = 9090
    external = ${host_port_b}
    protocol = "tcp"
  }
]

container_env = {
  DEFAULT_SERVICES_MODE = "auto"
  ENTRYPOINT_LOG_LEVEL  = "info"
}
EOF
  } > "${CONFIG_FILE}"

  echo
  echo "Saved your answers to ${CONFIG_FILE}."
}

require_cmd terraform
require_cmd docker

create_config_if_needed

echo "Running terraform init..."
terraform -chdir="${TF_DIR}" init -input=false
echo "Terraform ready."

echo "Running terraform ${ACTION}..."

case "${ACTION}" in
  plan)
    terraform -chdir="${TF_DIR}" plan -input=false
    ;;
  apply)
    terraform -chdir="${TF_DIR}" apply -auto-approve -input=false
    echo
    echo "Maestro is provisioned. Current outputs:"
    terraform -chdir="${TF_DIR}" output
    echo
    echo "Use './iac/provision.sh destroy' when you are ready to tear everything down."
    ;;
  destroy)
    terraform -chdir="${TF_DIR}" destroy -auto-approve -input=false
    echo "Maestro resources destroyed."
    ;;
esac
